# Generated by Django 4.1.4 on 2022-12-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='review',
            new_name='text',
        ),
    ]
